/**:
  ros__parameters:
    pddl_manager_plugin: "easy_plan_knowledge_graph/KgPddlManager"
    planner_plugin: "easy_plan_smtp/SmtpPlanner"
    plan_validator_plugin: "easy_plan_popf/PopfValidator"
    actions_plugins:
      - "easy_plan_demos/MoveYasminAction"
      - "easy_plan_demos/ChargeAction"
      - "easy_plan_demos/AskChargeAction"
    domain_requirements:
      - "typing"
      - "negative-preconditions"
      - "durative-actions"
