/**:
  ros__parameters:
    pddl_manager:
      domain_requirements:
        - "typing"
        - "negative-preconditions"
        - "durative-actions"
      plugin: "easy_plan_knowledge_graph/KgPddlManager"
    planner:
      plugin: "easy_plan_smtp/SmtpPlanner"
    plan_validator:
      plugin: "easy_plan_popf/PopfValidator"
    actions_plugins: [""]
