/omni_plan_node:
  ros__parameters:
    # Enable publishing state machine data for viewer
    enable_viewer_pub: true

    pddl_manager:
      plugin: "omni_plan_knowledge_base/KbPddlManager"
      # Domain requirements
      domain_requirements:
        - "typing"
        - "negative-preconditions"
        - "durative-actions"

    planner:
      plugin: "omni_plan_vhpop/VhpopPlanner"
      # Action cost value
      action_cost: 0.0
      # Domain constraints parameter (0: prune static preconditions, otherwise keep)
      domain_constraints: 1
      # Flaw selection order
      flaw_order: ""
      # Use ground actions
      ground_actions: false
      # Heuristic to rank plans
      heuristic: ""
      # Search no more than this number of plans
      limit: -1
      # Add open conditions in random order
      random_open_conditions: false
      # Seed for random number generator
      seed: 0
      # Search algorithm
      search_algorithm: ""
      # Time limit in minutes
      time_limit: 1
      # Tolerance for durative actions
      tolerance: 0.01
      # Weight for heuristic
      weight: 1.0

    plan_validator:
      plugin: "omni_plan_val/ValValidator"
      # Tolerance value for validation (float)
      tolerance: 0.0
      # Robustness analysis parameters: n (timestamp tolerance), p (PNE tolerance), m (number of test plans)
      robustness_n: 0.0
      robustness_p: 0.0
      robustness_m: 0
      # Robustness for action timestamps with PNE tolerance p
      robustness_action_p: 0.0
      # Robustness for PNEs with timestamp tolerance n
      robustness_pne_n: 0.0
      # Metric for robustness testing: "m" (maximum), "a" (accumulative), "d" (delay)
      robustness_metric: "m"
      # Distribution for robustness testing: "u" (uniform), "n" (normal), "p" (pseudo-normal)
      robustness_distribution: "u"
      # Vary PNEs for event preconditions
      vary_event_preconditions: false
      # Use graphplan length where no metric specified
      use_graphplan_length: false
      # Check set of derived predicates for stratification
      check_derived_predicates: true
      # Continue executing plan even if an action precondition is unsatisfied
      continue_on_precondition_fail: false
      # Produce error report for the full plan and try to repair it
      produce_error_report: false
      # Warn if invariants with continuous effects cannot be checked
      warn_invariants: false
      # Use makespan as metric for temporal plans
      use_makespan_metric: false

    actions_plugins:
      - "omni_plan_demos/MoveBtAction"
      - "omni_plan_demos/ChargeAction"
      - "omni_plan_demos/AskChargeAction"
    move_action:
      increment: 0.05
      plugins:
        - "move_bt_node"
      enable_groot_monitoring: false
      max_msg_per_second: 10
      publisher_port: 1666
      server_port: 1667
    charge_action:
      increment: 0.05
    ask_charge_action:
      increment: 0.05
