// Copyright (C) 2025 Miguel Ángel González Santamarta
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#ifndef EASY_PLAN__POPF_VALIDATOR_HPP_
#define EASY_PLAN__POPF_VALIDATOR_HPP_

#include <memory>
#include <string>

#include "easy_plan/pddl/plan.hpp"
#include "easy_plan/plan_validator.hpp"

namespace easy_plan_popf {

/**
 * @class PopfValidator
 * @brief Plan validator implementation for POPF-generated plans.
 * @details This class extends the base PlanValidator to provide validation
 * specifically tailored for plans created by the POPF planner. It handles
 * the temporal and durative action aspects that POPF plans may include.
 */
class PopfValidator : public easy_plan::PlanValidator {
public:
  /**
   * @brief Default constructor for PopfValidator.
   * @details Initializes the POPF plan validator with default settings.
   */
  PopfValidator();

  /**
   * @brief Validates a plan using POPF-specific validation logic.
   * @details Performs validation on plans generated by POPF, taking into
   * account temporal constraints, durative actions, and other POPF-specific
   * features. Ensures that the plan is executable and achieves the specified
   * goals.
   * @param domain The PDDL domain definition as a string.
   * @param problem The PDDL problem definition as a string.
   * @param plan The plan to validate.
   * @return True if the plan is valid according to POPF semantics, false
   * otherwise.
   */
  bool validate_plan(const std::string &domain_path,
                     const std::string &problem_path,
                     const std::string &plan_path) const override;

  /**
   * @brief Parses a PDDL plan string into a Plan object.
   * @details Converts a PDDL plan represented as a string into a Plan object
   * that can be processed and validated.
   * @param plan The PDDL plan as a string.
   * @return A Plan object representing the parsed plan.
   */
  std::string parse_pddl(const easy_plan::pddl::Plan &plan) const override;

private:
};

} // namespace easy_plan_popf
#endif // EASY_PLAN__POPF_VALIDATOR_HPP_