// Copyright (C) 2025 Miguel Ángel González Santamarta
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#ifndef EASY_PLAN_VAL__VAL_VALIDATOR_HPP_
#define EASY_PLAN_VAL__VAL_VALIDATOR_HPP_

#include <memory>
#include <string>

#include "easy_plan/pddl/plan.hpp"
#include "easy_plan/plan_validator.hpp"

namespace easy_plan_val {

/**
 * @class ValValidator
 * @brief Plan validator implementation for VAL-generated plans.
 * @details This class extends the base PlanValidator to provide validation
 * specifically tailored for plans created by the VAL validator. It handles
 * the temporal and durative action aspects that VAL plans may include.
 */
class ValValidator : public easy_plan::PlanValidator {
public:
  /**
   * @brief Default constructor for ValValidator.
   * @details Initializes the VAL plan validator with default settings.
   */
  ValValidator();

  /**
   * @brief Validates a plan using VAL-specific validation logic.
   * @details Performs validation on plans generated by VAL, taking into
   * account temporal constraints, durative actions, and other VAL-specific
   * features. Ensures that the plan is executable and achieves the specified
   * goals.
   * @param domain The PDDL domain definition as a string.
   * @param problem The PDDL problem definition as a string.
   * @param plan The plan to validate.
   * @return True if the plan is valid according to VAL semantics, false
   * otherwise.
   */
  bool validate_plan(const std::string &domain_path,
                     const std::string &problem_path,
                     const std::string &plan_path) const override;

  /**
   * @brief Parses a PDDL plan string into a Plan object.
   * @details Converts a PDDL plan represented as a string into a Plan object
   * that can be processed and validated.
   * @param plan The PDDL plan as a string.
   * @return A Plan object representing the parsed plan.
   */
  std::string parse_pddl(const easy_plan::pddl::Plan &plan) const override;

private:
  /// @brief Tolerance value for validation (float).
  float tolerance_;
  /// @brief Robustness analysis parameters: n (timestamp tolerance), p (PNE
  /// tolerance), m (number of test plans).
  float robustness_n_;
  float robustness_p_;
  int robustness_m_;
  /// @brief Robustness for action timestamps with PNE tolerance p.
  float robustness_action_p_;
  /// @brief Robustness for PNEs with timestamp tolerance n.
  float robustness_pne_n_;
  /// @brief Metric for robustness testing: "m" (maximum), "a" (accumulative),
  /// "d" (delay).
  std::string robustness_metric_;
  /// @brief Distribution for robustness testing: "u" (uniform), "n" (normal),
  /// "p" (pseudo-normal).
  std::string robustness_distribution_;
  /// @brief Vary PNEs for event preconditions.
  bool vary_event_preconditions_;
  /// @brief Use graphplan length where no metric specified.
  bool use_graphplan_length_;
  /// @brief Check set of derived predicates for stratification.
  bool check_derived_predicates_;
  /// @brief Continue executing plan even if an action precondition is
  /// unsatisfied.
  bool continue_on_precondition_fail_;
  /// @brief Produce error report for the full plan and try to repair it.
  bool produce_error_report_;
  /// @brief Warn if invariants with continuous effects cannot be checked.
  bool warn_invariants_;
  /// @brief Use makespan as metric for temporal plans.
  bool use_makespan_metric_;
};

} // namespace easy_plan_val
#endif // EASY_PLAN_VAL__VAL_VALIDATOR_HPP_